package Vehiculos.entity;
// Generated 05-jun-2016 22:32:38 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Coches generated by hbm2java
 */
public class Coches  implements java.io.Serializable {

/**
 * @param variables de la clase
 */
     private Integer idVehiculo;
     private String matricula;
     private String modelo;
     private String reparacion;
     private String fechaRep;
     private String kilometros;
     private String operario;
     /**
      * constructor de la clase sin parámetros
      */
    public Coches() {
    }
/**
 * Constructor de la clase con parámetros
 * @param matricula
 * @param modelo
 * @param reparacion
 * @param fechaRep
 * @param kilometros
 * @param operario 
 */
    public Coches(String matricula, String modelo, String reparacion, String fechaRep,String kilometros,String operario) {
       this.matricula = matricula;
       this.modelo = modelo;
       this.reparacion = reparacion;
       this.fechaRep = fechaRep;
       this.kilometros = kilometros;
       this.operario = operario;
    }
/**
 * 
 * @return devuelve los kilómetros
 */
    public String getKilometros() {
        return kilometros;
    }
/**
 * 
 * @param kilometros inserta kilómetros
 */
    public void setKilometros(String kilometros) {
        this.kilometros = kilometros;
    }
/**
 * 
 * @return devuelve el operario
 */
    public String getOperario() {
        return operario;
    }
/**
 * 
 * @param operario inserta operario
 */
    public void setOperario(String operario) {
        this.operario = operario;
    }
   /**
    * 
    * @return clave primaria
    */
    public Integer getIdVehiculo() {
        return this.idVehiculo;
    }
    /**
     * 
     * @param idVehiculo inserta clave primaria
     */
    public void setIdVehiculo(Integer idVehiculo) {
        this.idVehiculo = idVehiculo;
    }
    /**
     * @return matricula del vehículo
     */
    public String getMatricula() {
        return this.matricula;
    }
    /**
     * 
     * @param matricula inserta matricula
     */
    public void setMatricula(String matricula) {
        this.matricula = matricula;
    }
    /**
     * @return modelo vehículo
     */
    public String getModelo() {
        return this.modelo;
    }
    /**
     * @param modelo inserta modelo
     */
    public void setModelo(String modelo) {
        this.modelo = modelo;
    }
    /**
     * 
     * @return trabajos realizados
     */
    public String getReparacion() {
        return this.reparacion;
    }
    /**
     * @param reparacion inserta reparación realizada
     */
    public void setReparacion(String reparacion) {
        this.reparacion = reparacion;
    }
    /**
     * devuelve la fecha de reparación
     * @return 
     */
    public String getFechaRep() {
        return this.fechaRep;
    }
    /**
     * inserta la fecha de reparación
     * @param fechaRep 
     */
    public void setFechaRep(String fechaRep) {
        this.fechaRep = fechaRep;
    }




}


